apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::351240267287:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9R9WQ204GBQC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::351240267287:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-11T20:02:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1265"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d193a183-e587-4cb1-9a95-e44b082a1fad
